---
- name: Attempt to install tailscale
  block:
    - name: Install tailscale
      include_role:
        name: artis3n.tailscale.machine

  rescue:
    - name: Check if error is permission related
      fail:
        msg: "Non-permission error detected: {{ ansible_failed_result.msg[0] }}"
      when: "'calling actor does not have enough permissions' not in ansible_failed_result.msg[0]"

    - name: Set tailscale operator
      become: yes
      shell: tailscale set --operator={{ ansible_user }}
      register: permission_fix_result
      changed_when: permission_fix_result.rc == 0

    - name: Attempt a retry tailscale installation
      include_role:
        name: artis3n.tailscale.machine
