---
- name: Perform an upgrade
  become: yes
  ansible.builtin.apt:
    upgrade: full
    update_cache: true

- name: Remove dependencies that are no longer required.
  become: yes
  ansible.builtin.apt:
    autoremove: yes

- name: Check if a reboot is required.
  ansible.builtin.stat:
    path: /var/run/reboot-required
    get_checksum: no
  register: reboot_required_file

- name: Reboot the server (if required).
  become: yes
  ansible.builtin.reboot:
  when: reboot_required_file.stat.exists == true